### ISSUE TITLE
Windows Subsystem Linux usage 

### ISSUE THREAD

**Issue by spences10** [kentcdodds/netlify-shortener#5]
- `netlify-shortener` version:1.0.3
- `node` version:10.14.2
- `npm` (or `yarn`) version:6.4.1

Relevant code or config

```javascript
```

What you did: tried to run `shorten` for the npm script `netlify-shortener`

What happened: got the following error output:

```text
/m/c/U/s/g/netlify-short-urls ⎇ feat/use-netlify-shortner ○
❯ nr shorten                                                                                                                              ⬢ v10.14.2
> netlify-short-urls@1.0.0 shorten /mnt/c/Users/spenc/gitrepos/netlify-short-urls 
> netlify-shortener

committing: format links 
On branch feat/use-netlify-shortner 
Your branch is up to date with 'origin/feat/use-netlify-shortner'.

nothing to commit, working tree clean
pushing 
Everything up-to-date 
/mnt/c/Users/spenc/gitrepos/netlify-short-urls/node_modules/clipboardy/lib/linux.js:10 
        throw err;
        ^

Error: xsel: Can't open display: (null) 
: Inappropriate ioctl for device

    at Function.module.exports.sync (/mnt/c/Users/spenc/gitrepos/netlify-short-urls/node_modules/execa/index.js:303:26)
    at Object.copySync (/mnt/c/Users/spenc/gitrepos/netlify-short-urls/node_modules/clipboardy/lib/linux.js:31:18)
    at Object.exports.writeSync.input [as writeSync] (/mnt/c/Users/spenc/gitrepos/netlify-short-urls/node_modules/clipboardy/index.js:38:13)        
    at Object.<anonymous> (/mnt/c/Users/spenc/gitrepos/netlify-short-urls/node_modules/netlify-shortener/dist/index.js:46:12)
    at Module._compile (internal/modules/cjs/loader.js:689:30) 
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
npm ERR! code ELIFECYCLE 
npm ERR! errno 1 
npm ERR! netlify-short-urls@1.0.0 shorten: `netlify-shortener` 
npm ERR! Exit status 1
npm ERR!  
npm ERR! Failed at the netlify-short-urls@1.0.0 shorten script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in: 
npm ERR!     /home/scott/.npm/_logs/2019-01-04T08_19_08_897Z-debug.log

/m/c/U/s/g/netlify-short-urls ⎇ feat/use-netlify-shortner ○
```

Reproduction repository: spences10/netlify-short-urls

Problem description: I'm using WSL so not sure if that is an issue or the fact that I'm on a feature branch and not master

Suggested solution: looking into CD settings on netlify now

**Comment by spences10** [comment]
I pushed these changes to master and still get the error but the link is being added

**Comment by kentcdodds** [comment]
This is failing here:

https://github.com/kentcdodds/netlify-shortener/blob/c66b19ed33be6a3c0673674865cbbc5fb7156cdc/src/index.js#L40

I'm not sure why it's not working for you but I'm guessing this is a [clipboardy](https://npm.im/clipboardy) bug. Could you do a little digging to figure out what's going on there?

**Comment by LekoArts** [comment]
It's an issue with WSL itself. There are some (weird) solutions though:
- https://www.reddit.com/r/bashonubuntuonwindows/comments/4xzls0/accessing_windows_clipboard_through_xsel/
- https://askubuntu.com/questions/1035903/how-can-i-get-around-using-xclip-in-the-linux-subsystem-on-win-10
- https://github.com/Microsoft/WSL/issues/1069#issuecomment-363990534
- https://github.com/Microsoft/WSL/issues/2975

It seems `cat filepath | clip.exe` is the easiest one.

**Comment by LekoArts** [comment]
Changing the index.js to this made it work on WSL:

```js
#!/usr/bin/env node

/* istanbul ignore file */
"use strict";

const fs = require('fs');

const path = require('path');

const { exec } = require('child_process');

const readPkg = require('read-pkg-up');

const {
  format,
  generateCode,
  commitAndPush,
  validateUrl,
  validateUnique
} = require('./utils');

const {
  pkg: {
    baseUrl = 'https://update-baseUrl-in-your-package.json'
  },
  path: pkgPath
} = readPkg.sync({
  cwd: path.join(__dirname, '../..')
});
const repoRoot = path.dirname(pkgPath);
const redirectPath = path.join(repoRoot, '_redirects');
const [,, longLink, code] = process.argv;
const short = `/${code || generateCode()}`;
const contents = fs.readFileSync(redirectPath, 'utf8');
let newContents = contents;

if (longLink) {
  validateUrl(longLink);
  validateUnique(short, contents);
  newContents = `${short} ${longLink}\n${contents}`;
}

fs.writeFileSync(redirectPath, format(newContents));
commitAndPush(short, longLink, repoRoot);
const link = `${baseUrl}${short}`;
exec(`echo "${link}" | clip.exe`, (err, stdout) => {
  if (err) {
    console.log('Erorr copying the link into your clipboard')
    return
  }
  console.log(`${link} has been copied to your clipboard`);
});
```

**Comment by spences10** [comment]
Closing, I'm working around the issue.
